name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - main
  
env:
  NETCORE_VERSION: '3.1.402'
  GIT_REPO_ROOT: src
  SOLUTION_FILE: Snippets.sln
  UNITTEST_PROJECT_PATH: Snippets/Snippets.UnitTests/Snippets.UnitTests.csproj

jobs:
    build:
        name: Build and Unit Test
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: ${{ env.NETCORE_VERSION }}
        - name: Restore packages
          working-directory: ${{ env.GIT_REPO_ROOT }}
          run: dotnet restore ${{ env.SOLUTION_FILE }}
        - name: Build app
          working-directory: ${{ env.GIT_REPO_ROOT }}
          run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Debug --no-restore
        - name: Run Unit Tests
          working-directory: ${{ env.GIT_REPO_ROOT }}
          run: dotnet test ${{ env.UNITTEST_PROJECT_PATH }} --no-build --collect:"XPlat Code Coverage"
